### ISSUE TITLE
Update caching to use a flag instead of preferCache boolean.

### ISSUE THREAD

**Issue by andrewshell** [andrewshell/fedwikifeeds#1]
Example of using an enum: 0=OnlyFresh 1=CachedOnFailure 2=PreferCache 3=OnlyCache

**Comment by 0pdd** [comment]
@andrewshell 4 puzzles [#10](https://github.com/andrewshell/fedwikifeeds/issues/10), [#11](https://github.com/andrewshell/fedwikifeeds/issues/11), [#8](https://github.com/andrewshell/fedwikifeeds/issues/8), [#9](https://github.com/andrewshell/fedwikifeeds/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@andrewshell 2 puzzles [#10](https://github.com/andrewshell/fedwikifeeds/issues/10), [#11](https://github.com/andrewshell/fedwikifeeds/issues/11) are still not solved; solved: [#8](https://github.com/andrewshell/fedwikifeeds/issues/8), [#9](https://github.com/andrewshell/fedwikifeeds/issues/9).

**Comment by 0pdd** [comment]
@andrewshell all 4 puzzles are solved here: [#10](https://github.com/andrewshell/fedwikifeeds/issues/10), [#11](https://github.com/andrewshell/fedwikifeeds/issues/11), [#8](https://github.com/andrewshell/fedwikifeeds/issues/8), [#9](https://github.com/andrewshell/fedwikifeeds/issues/9).
