### ISSUE TITLE
Make sections grouped by wiki site collapsible

### ISSUE THREAD

**Issue by Bortseb** [andrewshell/fedwikifeeds#12]
I just noticed on http://fedwikiriver.com/ that the river is grouped by edits that happened on the same wiki site. Sometimes these groupings are very long. It would be nice if clicking on the header of the panel collapsed to only show the site name, and time, and maybe how many items are contained within...

Would this be a fairly simple enhancement? I'm not skilled enough at web UI play to answer this, or code this myself... but would love to co-work on it if it's something that's easy for you to do and you don't mind narrating a bit while you work :P 

Anyhow, thanks for this awesome service!

**Comment by andrewshell** [comment]
This is a great idea. I should be able to add this without too much trouble.

**Comment by andrewshell** [comment]
Collapsable groups have been implemented and deployed to http://fedwikiriver.com/

Let me know if this is what you had in mind.

**Comment by Bortseb** [comment]
> Let me know if this is what you had in mind.

Yep! Thanks
